Rd 5977 validate input types are matching dsl version
cloudify-cosmo/cfy-lint pull request #49
Opened 2022-10-25 11:39 UTC by kaplanyaniv

2022-10-26 18:09 UTC, EarthmanT commented on cfy_lint/yamllint_ext/rules/inputs.py
> +        yield LintProblem(line, None, 'input "{}" of type "{}" doesn\'t work '
Let's improve this problem message. Like `"Input of type {} is not supported by DSL {}."`.

2022-10-26 18:09 UTC, EarthmanT commented on cfy_lint/yamllint_ext/rules/inputs.py
> +                         'dict', 'regex', 'textarea'],
Yeah we support `textarea`?

2022-10-26 18:09 UTC, EarthmanT commented on cfy_lint/yamllint_ext/rules/inputs.py
> +                         'deployment_ids', 'blueprint_ids']}
I would find a way for 1_4 to be:
```
DSL_14 = DSL_13.extend([blueprint_id, ...])
```

2022-10-27 13:58 UTC, kaplanyaniv commented on cfy_lint/yamllint_ext/rules/inputs.py
> +                         'dict', 'regex', 'textarea'],
I asked mateusz and he told me that we do, I never saw it being used but apparently we do

2022-10-27 14:36 UTC, EarthmanT requested changes

2022-10-27 15:56 UTC, EarthmanT approved these changes

2022-10-27 15:57 UTC, merged